server:
  port: 8087

spring:
  application:
    name: Spring Project v2

  datasource:
    url: jdbc:postgresql://localhost:5432/bebka
    username: postgres
    password: 1116
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      secret-key: hTFkS1u7leoyuCYMmhGlwVV61EdUFTdJ64B8QjtiX/4=